import { defineConfig } from "astro/config";
import sitemap from "@astrojs/sitemap";
import mdx from "@astrojs/mdx";
import pagefind from "astro-pagefind";
import tailwindcss from "@tailwindcss/vite";
import partytown from "@astrojs/partytown";
import sitemap from "@astrojs/sitemap";
import robotsTxt from 'astro-robots-txt';

// https://astro.build/config
export default defineConfig({
  site: "https://eddiewelker.com",
  integrations: [
      sitemap(),
      mdx(),
      pagefind(),
      sitemap(),
      partytown({
        // This is necessary to tell Partytown to handle GA events
        forward: ['dataLayer.push'],
      }),
      robotsTxt({
      sitemapBaseFileName: 'sitemap-index', // Matches default astro-sitemap name
      policy: [
        {
          userAgent: '*',
          allow: '/',
          // Optional: Block things you don't want indexed
          disallow: ['/admin/', '/private/'],
        },
      ],
    }),
  ],
  vite: {
    plugins: [tailwindcss()],
  },
  markdown: {
    shikiConfig: {
      theme: "css-variables",
    },
  },

  redirects: {
    '/2007/10/20/concert-tonight': '/blog/concert-tonight',
    '/2008/02/10/writing-scheme-in-javascript-i': '/blog/writing-scheme-in-javascript-i',
    '/2007/09/01/all-this-traffic': '/blog/all-this-traffic',
    '/2007/10/22/game-7-i-think-kenny-lofton-was-out-at-second': '/blog/game-7-i-think-kenny-lofton-was-out-at-second',
    '/2007/08/15/prelude': '/blog/prelude',
    '/2007/10/25/firefox-for-mac-and-displaying-small-font-sizes': '/blog/firefox-for-mac-and-displaying-small-font-sizes',
    '/2007/08/30/18': '/blog/18',
    '/2009/08/03/check-in': '/blog/check-in',
    '/2008/03/27/its-about-time': '/blog/its-about-time',
    '/2007/08/21/ie-6-background-flicker-problem': '/blog/ie-6-background-flicker-problem',
    '/2009/01/09/sibelius-symphony-no-1': '/blog/sibelius-symphony-no-1',
    '/2008/08/04/review-of-web-form-design-filling-in-the-blanks': '/blog/review-of-web-form-design-filling-in-the-blanks',
    '/2007/12/17/jean-edward-welker': '/blog/jean-edward-welker',
    '/2013/05/15/wing-contest-at-quarry-house': '/blog/wing-contest-at-quarry-house',
    '/2008/04/13/python': '/blog/python',
    '/2008/03/04/throwing-ie8-in-acid': '/blog/throwing-ie8-in-acid',
    '/2011/08/03/onion-dill-rice': '/blog/onion-dill-rice',
    '/2008/07/15/le-tour': '/blog/le-tour',
    '/2008/04/01/php-and-me': '/blog/php-and-me',
    '/2008/05/23/getting-a-button-elements-value-attribute-not-innerhtml-in-ie': '/blog/getting-a-button-elements-value-attribute-not-innerhtml-in-ie',
    '/2008/10/25/object-oriented-javascript-review': '/blog/object-oriented-javascript-review',
    '/2007/09/18/thought-for-the-day': '/blog/thought-for-the-day',
    '/2011/07/12/relatively-quick-pizza-from-scratch': '/blog/relatively-quick-pizza-from-scratch',
    '/2009/01/08/top-5-xslt-books': '/blog/top-5-xslt-books',
    '/2007/11/10/weekend': '/blog/weekend',
    '/2009/09/09/boring-i-moved-post': '/blog/boring-i-moved-post',
    '/2025/09/01/szechuan_noodles': '/blog/szechuan_noodles',
    '/2008/07/07/review-of-learning-website-development-with-django': '/blog/review-of-learning-website-development-with-django',
    '/2009/01/25/review-of-expert-python-programming': '/blog/review-of-expert-python-programming',
    '/2007/08/17/4': '/blog/4',
    '/2008/09/03/django-10': '/blog/django-10',
    '/2009/09/24/review-of-learning-jquery-1-3': '/blog/review-of-learning-jquery-1-3',
    '/2007/11/19/review-of-high-performance-web-sites': '/blog/review-of-high-performance-web-sites',
    '/2008/02/21/i-was-going-to-write-tonight': '/blog/i-was-going-to-write-tonight',
    '/2007/10/02/playoffs': '/blog/playoffs',
    '/2009/08/12/bad-chain-tool-bad': '/blog/bad-chain-tool-bad',
    '/2007/08/26/red-sox-sweep-white-sox': '/blog/red-sox-sweep-white-sox',
    '/2008/12/27/xslt-copy-copy-of': '/blog/xslt-copy-copy-of',
    '/2007/08/20/moving-but-not-yet': '/blog/moving-but-not-yet',
    '/2007/08/28/i-looked-i-purchased': '/blog/i-looked-i-purchased',
    '/2011/04/06/high-performance-css-code-design': '/blog/high-performance-css-code-design',
    '/2007/11/08/time-for-small-celebration': '/blog/time-for-small-celebration',
    '/2007/12/28/cats-out-of-the-bag': '/blog/cats-out-of-the-bag',
    '/2009/03/31/url-fairy-tales': '/blog/url-fairy-tales',
    '/2007/10/23/not-the-worst-movie-ever-and-the-worst': '/blog/not-the-worst-movie-ever-and-the-worst',
    '/2008/10/16/october-horror-movies': '/blog/october-horror-movies',
    '/2007/10/23/xslt-class': '/blog/xslt-class',
    '/2008/01/22/ie8-doctype-and-potentially-broken-default-behavior': '/blog/ie8-doctype-and-potentially-broken-default-behavior',
    '/2014/03/16/st-patricks-day-corned-beef-and-cabbage-irish-soda-bread': '/blog/st-patricks-day-corned-beef-and-cabbage-irish-soda-bread',
    '/2007/08/27/opera-9-and-decimal-em-lengths': '/blog/opera-9-and-decimal-em-lengths',
    '/2008/01/20/twitter-inspires-similar-thoughts-when-broken': '/blog/twitter-inspires-similar-thoughts-when-broken',
    '/2007/12/18/another-design-tweak': '/blog/another-design-tweak',
    '/2007/08/20/internet-explorer-6-still-stinks': '/blog/internet-explorer-6-still-stinks',
    '/2008/04/27/my-first-flickr-video': '/blog/my-first-flickr-video',
    '/2007/11/16/photos': '/blog/photos',
    '/2008/10/26/more-october-horror-movies': '/blog/more-october-horror-movies',
    '/2007/10/18/class-over': '/blog/class-over',
    '/2008/01/21/finally-i-get-feedburner': '/blog/finally-i-get-feedburner',
    '/2007/08/20/being-different': '/blog/being-different',
    '/2009/01/29/review-of-prototype-based-programming': '/blog/review-of-prototype-based-programming',
    '/2007/09/06/css-shorthand-cheat-sheet': '/blog/css-shorthand-cheat-sheet',
    '/2007/10/03/catching-up': '/blog/catching-up',
    '/2007/09/25/95-done-moving': '/blog/95-done-moving',
    '/2008/12/18/affecting-your-situation': '/blog/affecting-your-situation',
    '/2008/06/20/down-to-three-bugs': '/blog/down-to-three-bugs',
    '/2008/09/18/funny-thing-about-bugs': '/blog/funny-thing-about-bugs',
    '/2008/04/04/86': '/blog/86',
    '/2007/12/31/thanks': '/blog/thanks',
    '/2009/08/24/cutting-scheme-in-half': '/blog/cutting-scheme-in-half',
    '/2008/11/11/horror-movies-final-installment': '/blog/horror-movies-final-installment',
    '/2008/12/28/recursive-xslt-templates': '/blog/recursive-xslt-templates',
    '/2008/03/09/using-the-label-element-for-form-accessibility': '/blog/using-the-label-element-for-form-accessibility',
    '/2010/03/31/installing-pil-virtualenv-ubuntu': '/blog/installing-pil-virtualenv-ubuntu',
    '/2007/09/12/blurry-focus': '/blog/blurry-focus',
    '/2008/01/08/back-on-two-wheels': '/blog/back-on-two-wheels',
    '/2007/12/18/editing-live': '/blog/editing-live',
    '/2008/03/05/big-release-day-on-the-webbernet': '/blog/big-release-day-on-the-webbernet',
    '/2008/03/04/microsoft-takes-giant-pr-step-with-ie8-default-behavior': '/blog/microsoft-takes-giant-pr-step-with-ie8-default-behavior',
    '/2008/07/17/clean-room': '/blog/clean-room',
    '/2008/01/16/what-ive-been-up-to': '/blog/what-ive-been-up-to',
    '/2007/10/03/rss-newsreaders': '/blog/rss-newsreaders',
    '/2007/10/10/problem-du-jour-firefox-fonts': '/blog/problem-du-jour-firefox-fonts',
    '/2008/01/26/the-ie8-doctype-meta-waiting-game': '/blog/the-ie8-doctype-meta-waiting-game',
    '/2008/11/25/push-style-xslt-vs-pull-style': '/blog/push-style-xslt-vs-pull-style',
    '/2008/10/30/next-to-last-horror-movies': '/blog/next-to-last-horror-movies',
    '/2007/10/30/i-just-killed-wordpress': '/blog/i-just-killed-wordpress',
    '/2007/10/03/tbs-broadcasting-the-red-sox-playoff-game': '/blog/tbs-broadcasting-the-red-sox-playoff-game',
    '/2007/11/13/long-3-day-weekend': '/blog/long-3-day-weekend',
    '/2007/10/30/microformats-for-you-and-me': '/blog/microformats-for-you-and-me',
    '/2008/07/04/july-4': '/blog/july-4',
    '/2007/12/30/random-thoughts': '/blog/random-thoughts',
    '/2007/08/22/ie-flicker-thought-we-had-a-solution': '/blog/ie-flicker-thought-we-had-a-solution',
    '/2008/01/08/update-to-some-random-thoughts': '/blog/update-to-some-random-thoughts',
    '/2007/09/12/cool-september-air': '/blog/cool-september-air',
    '/2007/12/19/wow': '/blog/wow',
    '/2007/10/30/sweet-now-ill-never-have-to-join-facebook': '/blog/sweet-now-ill-never-have-to-join-facebook',
    '/2008/03/18/uploaded-photos': '/blog/uploaded-photos',
    '/2007/09/04/pushing-browsers': '/blog/pushing-browsers',
    '/2008/03/01/random-february-thoughts': '/blog/random-february-thoughts',
    '/2007/12/05/minor-distractions': '/blog/minor-distractions',
    '/2007/08/22/extreme-early-review-of-advanced-dom-scripting': '/blog/extreme-early-review-of-advanced-dom-scripting',
    '/2008/01/13/website-usability-annoyance-no-1': '/blog/website-usability-annoyance-no-1',
    '/2007/08/19/expression-engine': '/blog/expression-engine',
    '/2007/08/22/oh-sweet-irony': '/blog/oh-sweet-irony',
    '/2007/08/26/beginning-of-the-fall-semester': '/blog/beginning-of-the-fall-semester',
    '/2007/10/12/whirlwind': '/blog/whirlwind',
    '/2007/09/01/minor-design-update': '/blog/minor-design-update',
    '/2008/06/01/happy-regular-expressions-day': '/blog/happy-regular-expressions-day',
    '/2008/10/08/snapshot-of-right-now': '/blog/snapshot-of-right-now',
  },
});
